### ISSUE TITLE
Kaspersky and two other AVs detect the extension as virus.

### ISSUE THREAD

**Issue by parasiteoflife** [devnull69/copy-links#5]
I got two warnings from the extension one was Adware and the other a Trojan. Here is the virustotal report of the crx file.
https://www.virustotal.com/gui/file-analysis/NDk4MDJiZGM4ZDk0YTE2ZDNlMTg2Yjk2ZGFhYWFhMzQ6MTU3ODc2MTg2Ng==/detection

Please, fix this, it must be a false positive. Although with the latest update on the chrome web store and lack of commits on the repo I suppose a new dev has taken control of the web store?
I don't know, I will stay way away from the web store extension until that is fixed.

**Comment by devnull69** [comment]
The extension you are talking about is not mine. My extension is not listed on Chrome Webstore

**Comment by parasiteoflife** [comment]
That was weird, I remember that I did check the link you have on the project description (https://chrome.google.com/webstore/detail/copy-links/kcpoommnneaebpfgaoejklgemonkmjpc) with the false positives. Now is gone from the Webstore.
