### ISSUE TITLE
Chrome detects this as malware

### ISSUE THREAD

**Issue by elig0n** [devnull69/copy-links#6]
and app was removed from Chrome store.

**Comment by devnull69** [comment]
The chrome extension you are talking about is not mine

**Comment by elig0n** [comment]
That's weird because the extension I have has the same ID as the link in this repo's title which is 404.
![](https://i.ibb.co/LPZpN2K/2020-04-24-191457-610x409-scrot.png)
Are you claiming not to be the owner of this extension ?

**Comment by revilo951** [comment]
I've just had the same thing. Not cool
